[package]
name = "railsite"
version = "0.1.0"
authors = ["Martin Hoffmann <hn@nvnc.de>"]

[dependencies]
futures = "0.1.7"
hyper = { git = "https://github.com/hyperium/hyper.git" }
raildata = { git = "https://github.com/railwayhistory/raildata.git" }

[[bin]]
name = "railsite"
doc = false
